#KubeJS Dev Properties
#Tue Feb 03 19:28:14 ICT 2026
logSkippedTags=false
logSkippedRecipes=false
logSkippedPlugins=true
debugInfo=false
strictTags=false
logAddedRecipes=false
logRemovedRecipes=false
logModifiedRecipes=false
logInvalidRecipeHandlers=true
dataPackOutput=false
logGeneratedData=false
logErroringRecipes=true
